# Schema for the configuration files of the AIMX theme.

aimx.settings:
  type: theme_settings
  label: "AIMX settings"
  mapping:
    aimx_library:
      type: integer
      label: "Library"
    aimx_sidebar_position:
      type: text
      label: "Sidebar Position"
    aimx_content_offset:
      type: integer
      label: "Offset"
    aimx_sidebar_first_width:
      type: integer
      label: "Width"
    aimx_sidebar_first_offset:
      type: integer
      label: "Offset"
    aimx_sidebar_second_width:
      type: integer
      label: "Width"
    aimx_sidebar_second_offset:
      type: integer
      label: "Offset"
    aimx_footer_layout:
      type: text
      label: "Layout"
    aimx_fluid_container:
      type: integer
      label: "Enabled"
    aimx_button_size:
      type: text
      label: "Size"
    aimx_button_outline:
      type: integer
      label: "Button outline"
    aimx_navbar_top_position:
      type: text
      label: "Position"
    aimx_navbar_top_color:
      type: integer
      label: "Color"
    aimx_navbar_top_background:
      type: text
      label: "Background"
    aimx_navbar_position:
      type: text
      label: "Position"
    aimx_navbar_color:
      type: integer
      label: "Color"
    aimx_navbar_background:
      type: text
      label: "Background"
    aimx_navbar_toggle:
      type: integer
      label: "Enable"
    aimx_navbar_container:
      type: text
      label: "Container"
